name: lm-eval
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py311h06a4308_0
  - python=3.11.7=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.27.2
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - attrs==23.2.0
      - certifi==2024.2.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - dataproperty==1.0.1
      - datasets==2.17.1
      - dill==0.3.8
      - distro==1.9.0
      - einops==0.7.0
      - filelock==3.13.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - h11==0.14.0
      - httpcore==1.0.3
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - idna==3.6
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonlines==4.0.0
      - markupsafe==2.1.5
      - mbstrdecoder==1.1.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - nltk==3.8.1
      - numexpr==2.9.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==1.12.0
      - packaging==23.2
      - pandas==2.2.0
      - pathvalidate==3.2.0
      - peft==0.8.2
      - portalocker==2.8.2
      - psutil==5.9.8
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pybind11==2.11.1
      - pycountry==23.12.11
      - pydantic==2.6.1
      - pydantic-core==2.16.2
      - pytablewriter==1.2.0
      - python-dateutil==2.8.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - rouge-score==0.1.2
      - sacrebleu==1.5.0
      - safetensors==0.4.2
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - six==1.16.0
      - sniffio==1.3.0
      - sqlitedict==2.1.0
      - sympy==1.12
      - tabledata==1.3.3
      - tcolorpy==0.1.4
      - threadpoolctl==3.3.0
      - tokenizers==0.15.2
      - torch==2.2.0
      - tqdm==4.66.2
      - tqdm-multiprocess==0.0.11
      - transformers==4.37.2
      - triton==2.2.0
      - typepy==1.3.2
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - xxhash==3.4.1
      - yarl==1.9.4
      - zstandard==0.22.0
prefix: /data/suhas_kotha/miniconda3/envs/lm-eval
